// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

/*
Package demo is a generated protocol buffer package.

It is generated from these files:
	demo.proto

It has these top-level messages:
	DemoReq
	DemoResp
*/
package demo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DemoReq struct {
	Call string `protobuf:"bytes,1,opt,name=call" json:"call,omitempty"`
}

func (m *DemoReq) Reset()                    { *m = DemoReq{} }
func (m *DemoReq) String() string            { return proto.CompactTextString(m) }
func (*DemoReq) ProtoMessage()               {}
func (*DemoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DemoReq) GetCall() string {
	if m != nil {
		return m.Call
	}
	return ""
}

type DemoResp struct {
	Reply string `protobuf:"bytes,1,opt,name=reply" json:"reply,omitempty"`
}

func (m *DemoResp) Reset()                    { *m = DemoResp{} }
func (m *DemoResp) String() string            { return proto.CompactTextString(m) }
func (*DemoResp) ProtoMessage()               {}
func (*DemoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DemoResp) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*DemoReq)(nil), "demo.DemoReq")
	proto.RegisterType((*DemoResp)(nil), "demo.DemoResp")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x64, 0xb9, 0xd8, 0x5d, 0x52,
	0x73, 0xf3, 0x83, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0x58, 0x92, 0x13, 0x73, 0x72, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x05, 0x2e, 0x0e, 0x88, 0x74, 0x71, 0x81, 0x90, 0x08,
	0x17, 0x6b, 0x51, 0x6a, 0x41, 0x4e, 0x25, 0x54, 0x01, 0x84, 0x93, 0xc4, 0x06, 0x36, 0xcd, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x60, 0xd9, 0xcc, 0x22, 0x5b, 0x00, 0x00, 0x00,
}
